# Use Java 8 official slim image
FROM openjdk:8-jdk-alpine

WORKDIR /app

# Copy the built jar from target folder
COPY target/*.jar app.jar

# Expose port 8080 (default Spring Boot port)
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]
